---
- name: update system
  apt: 
    name: "{{ packages }}"
  vars: 
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present 

- name:
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
    state: present 
    filename: docker 
    update_cache: yes

- name: install docker
  apt:
    name: "{{ packages }}"
  vars: 
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
