---
- name: update system
  apt: 
    name: "{{ packages }}"
  vars: 
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add GPG Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present 

- name: Add Docker Repository to System
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
    state: present 
    filename: docker 
    update_cache: yes

- name: install docker
  apt:
    name: "{{ packages }}"
  vars: 
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Enable Autocompletion for bash
  get_url:
    url: https://raw.githubusercontent.com/docker/compose/1.24.0/contrib/completion/bash/docker-compose
    dest: /etc/bash_completion.d/docker-compose
    mode: 0744
- name: Install docker-compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Set permission for docker-compose
  shell: chmod +x /usr/local/bin/docker-compose
